### ISSUE TITLE
Logausgaben sind wohl nicht STDOUT

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/raspager-proxy#13]
Das `` java -jar ../raspager-proxy/target/dapnet-proxy-1.0.9-jar-with-dependencies.jar db0dy.properties db0el.properties db0erf.properties db0fha.properties db0vox.properties db0zka.properties db0wv.properties dk0mav.properties > log.txt``
erzeugt eine leere log.txt und schreibt weiterhin auf den Schirm.

**Comment by Taronyu** [comment]
Der Logger aus java.util.logging loggt auch nicht nach STDOUT, sondern nach STDERR. Das ist also kein BUg der Anwendung. Wenn man den Logger konfigurieren möchte, muss man eine Config angeben, siehe beispielsweise [hier](https://de.wikibooks.org/wiki/Java_Standard:_Logging_API_von_Java).

Alternativ alles umleiten: `programm &> log.txt`
