### ISSUE TITLE
REST-API

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/raspager-proxy#14]
Die aktuelle Variante der JSON Ausgabe macht die Benutzung von https://github.com/drewkerrigan/nagios-http-json schwer, da man die Array-Position eines Senders kennen muss. Könnte man ein benanntes Array wie 
````
[
    {
        "sendername": {
            "state": "ONLINE", ....
        }
    }
]
````
machen? Oder vielleicht auch den Sender mittels Endpoint /status/sendername auswählen?

Zur Zeit sieht es noch so aus:
````
pi@monitoring /etc/nagios3 $ /usr/lib/nagios/plugins/check_http_json -H db0sda.ampr.org -P 8081 -p status -Q "(0).state,ONLINE"
OK: Status OK.
pi@monitoring /etc/nagios3 $ /usr/lib/nagios/plugins/check_http_json -H db0sda.ampr.org -P 8081 -p status -Q "(1).state,ONLINE"
CRITICAL: Status CRITICAL. Value for key (1).state did not match ONLINE.
pi@monitoring /etc/nagios3 $ /usr/lib/nagios/plugins/check_http_json -H db0sda.ampr.org -P 8081 -p status -Q "(2).state,ONLINE"
OK: Status OK.
pi@monitoring /etc/nagios3 $ /usr/lib/nagios/plugins/check_http_json -H db0sda.ampr.org -P 8081 -p status -Q "(3).state,ONLINE"
OK: Status OK.
pi@monitoring /etc/nagios3 $ /usr/lib/nagios/plugins/check_http_json -H db0sda.ampr.org -P 8081 -p status -Q "(4).state,ONLINE"
OK: Status OK.
pi@monitoring /etc/nagios3 $
````

**Comment by Taronyu** [comment]
Was wäre zum Abfragen einfacher? Ein Skript pro Sender oder ein Skript für alle?

**Comment by Taronyu** [comment]
Im master Branch ist ein Update, mit dem man zusätzlich über `/status/<Profilname>` nur den jeweiligen Server angezeigt bekommt. Das ist case-sensitive.

**Comment by Taronyu** [comment]
Ich habe noch einmal intern was mit der Dependency Injection der Manager-Klasse für die REST-API umgestellt. In meinem lokalen Test funktioniert das noch ;) Wenn alles klappt, baue ich aus der Version das neue Release.

**Comment by Taronyu** [comment]
Neues Release ist gebaut, Version 1.1.0.

**Comment by dh3wr** [comment]
Sehr gut, geht alles
![grafik](https://cloud.githubusercontent.com/assets/16710361/26297494/55f7e414-3ed3-11e7-8200-820519b3bb6e.png)
