### ISSUE TITLE
Programm-Name verwirrend, besser dapnet-proxy

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/raspager-proxy#2]
Der aktuelle Name raspager-proxy impliziert, dass es sich um einen Raspager handelt. Da aber auf lange Sicht die Raspager alle auf die neue Verbindungsrichtung mit RustPager geupdated sein werden, bleiben als Anwendungsfall nur noch die C9000 mit AX-25 (XOS) und PR430, sowie Exoten. Daher schlage ich vor, dieses Projekt in dapnet-proxy umzubenennen. Was meint ihr?

**Comment by 7h0ma5** [comment]
Finde ich gut, vielleicht noch etwas spezifischer: `dapnet-legacy-proxy` oder so ähnlich. Dann erkennt man sofort, dass es sich um eine Lösung für die alten Systeme handelt.

**Comment by Taronyu** [comment]
Ich habe den Namen geändert und die Readme angepasst. Den Pfad im Repository anzupassen, geht theoretisch auch, das muss man allerdings dann in allen ausgecheckten git Repos auch machen. Daher habe ich das erst einmal gelassen.
