### ISSUE TITLE
XOS Welcome Message passt nicht zu aktuellem Core Regex

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/raspager-proxy#3]
Beispiel von db0dy:
````[RPC/XOS 2.2.0pre32-SCP-#2345678]````
wird vom backend-Server geliefert, aber beim Core nach Durchlauf des DAPNET-Proxies als invalid erkannt.
Den Umbau könnte so geschehen: Zwar ohne Proxy-Erwähung nach https://github.com/DecentralizedAmateurPagingNetwork/Core/issues/51

aus ````[RPC/XOS 2.2.0pre32-SCP-#2345678]```` machen wir 
````
Name: XOS-RPC
Version: v.2.0pre36
````
Dann müssen wir aber auch das ````pre36```` erlauben in der Versionsnummer. Das müsste dann im Dapnet-Core geschehen.

**Comment by Taronyu** [comment]
Also diese XOS haben kein v-Präfix bei der Versionsnummer? Dann habe ich einen Fehler im Pattern.

Das pre36 ist jetzt schon drin, der Proxy schreibt die Message nur nicht um, da das Pattern nicht matcht. Dann fehlt halt auch Name/Passwort und das Pattern im Core matcht nicht.

**Comment by dh3wr** [comment]
Es gibt sowohl Versionen mit v als auch ohne.

**Comment by Taronyu** [comment]
Ist im Pattern jetzt als optional gesetzt.
