### ISSUE TITLE
Zeitsync für AX.25 basierte Sender fehlt im Core, daher hier

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/raspager-proxy#6]
Log:
```` 
000  -.
ax0: fm DB0FHN-3 to DB0ZKA-7 via DB0SDA IGATE ctl DISC+
ax0: fm DB0ZKA-7 to DB0FHN-3 via IGATE* DB0SDA* ctl UA-
ax0: fm DB0FHN-3 to DB0ZKA-7 via DB0SDA IGATE ctl SABM+
ax0: fm DB0ZKA-7 to DB0FHN-3 via IGATE* DB0SDA* ctl UA-
ax0: fm DB0ZKA-7 to DB0FHN-3 via IGATE* DB0SDA* ctl I00^ pid=F0(Text) len 25
0000  [PR430 0.57-SCP-#234567].
ax0: fm DB0FHN-3 to DB0ZKA-7 via DB0SDA IGATE ctl I10^ pid=F0(Text) len 8
0000  2:6499..
ax0: fm DB0ZKA-7 to DB0FHN-3 via IGATE* DB0SDA* ctl I11^ pid=F0(Text) len 14
0000  2:6499:5550.+.
ax0: fm DB0FHN-3 to DB0ZKA-7 via DB0SDA IGATE ctl I21^ pid=F0(Text) len 20
0000  4:0123456789ABCDEF..
ax0: fm DB0ZKA-7 to DB0FHN-3 via IGATE* DB0SDA* ctl I22^ pid=F0(Text) len 2
0000  -.
````

Hier fehlt die Nachricht ``3:`` mit der Zeit-Korrektur. Das ist wohl im Core nicht mehr drin. Müsste man dann hier implementieren. Ist sicher ein Aufwand, weil man nicht nur Durchreichen kann. Wird mit der Implementierung des neuen Sender-Protokolls dann nochmal nötig. Dann muss der proxy die ganzen 2: 3: und 4: Nachrichten erzeugen,

**Comment by Taronyu** [comment]
Hmm, das ist eigentlich noch im Core drinnen, die Methode `sendTimeAdjust()` in der Klasse `SyncTimeHandler`. Ist jetzt die Frage, ob das im Core oder im Proxy flöten geht. Ich habe da eher den Core im Verdacht.

**Comment by dh3wr** [comment]
ok, wenn der Core das doch macht... Schauen wir gleich mal nach.

**Comment by Taronyu** [comment]
Ist tatsächlich ein Bug im Core, ich habe das gerade mal mit Telnet simuliert.

**Comment by Taronyu** [comment]
Ich habe den Fehler gefunden. Das war ein fehlendes `break` in der SyncTimeHandler State Machine. ARRRRRRGH! Da ist aber noch was anderes faul.

**Comment by Taronyu** [comment]
Dürfte im Core gefixt sein.
