### ISSUE TITLE
Mehr als eine Verbindung ermöglichen

### ISSUE THREAD

**Issue by Taronyu** [rwth-afu/raspager-proxy#7]
Wenn man mehrere Proxyverbindungen von einem System aus herstellen möchte, dann muss man aktuell mehrere Instanzen des Proxys starten. Es wäre besser, wenn ein Proxy mehrere Verbindungen verwalten kann.

**Comment by dh3wr** [comment]
Die Parameter kann man dann evtl. in der Config durchnummerieren. Oder in Abschnitten angeben.

**Comment by Taronyu** [comment]
Ich möchte eigentlich keinen eigenen Config-Reader bauen, sondern das benutzen, was Java bereitstellt. Ich muss mal gucken, wie das zusammenpasst. Was momentan recht einfach machbar wäre, ist alle Konfigurationsdateien als Argument zu übergeben: `java -jar dapnet-proxy.jar config1.properties config2.properties`. Da müsste ich nur über eine for-Schleife Instanzen der Klasse `ProxyService` mit der passenden Config erzeugen. Zumindest theoretisch müsste das laufen.

**Comment by dh3wr** [comment]
Update Readme?

**Comment by Taronyu** [comment]
Ich hatte da schon etwas zu geschrieben. Wir müssten das aber noch einmal
vom master Branch testen. Sofern das alles funktioniert, baue ich ein neues
Release.

**Comment by dh3wr** [comment]
Alles klar. Kannst du gerne auf db0sda.ampr.org testen. Und ein Service wäre natürlich die Krönung :-)
