### ISSUE TITLE
Welcome regex passt für DB0RTV nicht

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/raspager-proxy#9]
Warum sich das auch immer geändert hat. 
https://github.com/rwth-afu/raspager-proxy/blob/master/src/main/java/de/rwth_aachen/afu/dapnet/proxy/WelcomeMessageEncoder.java

Ankommender String:
RPC/XOS 2.2.0pre32

Aktueller RegEx
\\[([/\\p{Alnum}]+) v?(\\d[\\d\\.]+[\\p{Graph}]*)]

Es scheint mit den eckigen Klammern zusammenzuhängen. Können wir die optional machen?

**Comment by Taronyu** [comment]
Gucke ich mir gleich mal an

**Comment by dh3wr** [comment]
Jetzt passt die Anmeldung am DAPNET-Core nicht mehr
Core sagt:
````
on from /84.187.46.243:56014
09:08:30.206 [nioEventLoopGroup-3-4] ERROR org.dapnet.core.transmission.ServerHandler - Closing connection: Invalid welcome message format: [UniPager-Dummy v0.5.0  ]
09:08:30.206 [nioEventLoopGroup-3-4] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
09:08:30.222 [nioEventLoopGroup-3-3] ERROR org.dapnet.core.transmission.ServerHandler - Closing connection: Invalid welcome message format: [[uPSDrpc/XOS v1.0b-SCP-#2345678] db0el test1234]
09:08:30.222 [nioEventLoopGroup-3-3] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
09:08:30.273 [nioEventLoopGroup-3-2] ERROR org.dapnet.core.transmission.ServerHandler - Closing connection: Invalid welcome message format: [[RPC/XOS v2.2.0pre36-SCP-#2345678] db0fha test1234]
09:08:30.273 [nioEventLoopGroup-3-2] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
09:08:30.936 [nioEventLoopGroup-3-1] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /44.225.164.2:49833
09:08:30.954 [nioEventLoopGroup-3-1] ERROR org.dapnet.core.transmission.ServerHandler - Closing connection: Invalid welcome message format: [[SDRPager v2.0-SCP-#2345678] db0kwe weisweiler]
09:08:30.954 [nioEventLoopGroup-3-1] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
09:08:31.282 [nioEventLoopGroup-3-2] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /84.187.46.243:56016
09:08:31.282 [nioEventLoopGroup-3-2] ERROR org.dapnet.core.transmission.ServerHandler - Closing connection: Invalid welcome message format: [UniPager-Dummy v0.5.0  ]

````
Da sind jetzt 2 "[" vorne...

**Comment by dh3wr** [comment]
Geht jetzt wieder mit allen außer DB0RTV
Hier der Core-Log
````
15:49:32.114 [nioEventLoopGroup-3-2] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /44.225.164.2:45966
15:49:32.818 [nioEventLoopGroup-3-2] ERROR org.dapnet.core.transmission.ServerHandler - Closing connection: Invalid welcome message format: RPC/XOS 2.2.0pre32
15:49:32.818 [nioEventLoopGroup-3-2] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
````

Wenn der Sender keine [ mitschickt, muss der Proxy eine hinzufügen.

Beispiel: Hier kein  Authkey, daher Fehler:
``n.ServerHandler - Closing connection: Invalid welcome message format: [UniPager-Dummy v0.5.0  ]``

**Comment by dh3wr** [comment]
Sorry, liegt an was anderem. Der Sender hat nicht unser Quell-Rufzeichen als Master eingestellt. Daher der Fehler. sorry nochmal

**Comment by dh3wr** [comment]
Evtl. können die Änderungen dann wieder rückgänig gemacht werden. Wenn ein Sender ohne "[" antwortet heißt dass wohl "Hau ab, ich mache dir nur die CLI auf, aber keine Master-Verbindung"

**Comment by Taronyu** [comment]
Der XOS/RPC String wird laut meiner Unit Tests transformiert. Ist das denn
die aktuelle Version? Ich hatte noch ein paar Probleme mit den doofen
Klammern...

**Comment by Taronyu** [comment]
Soll ich das dann wieder rausnehmen?

**Comment by dh3wr** [comment]
Ja, wie vorher war eignetlich ok. Wenn keine Klammer als erstes kommt dann liegt ein Fehler in der Sender-Konfig vor. Dann muss eigentlich gar keine Verbindung zum Core aufgebaut werden.

**Comment by Taronyu** [comment]
Ich habe es wieder auf die alte Version umgestellt.
